name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the public repo.
    - name: Checkout public repository
      uses: actions/checkout@v4
      
    # Step 2: Checkout the private repo into a 'nike' directory.
    - name: Checkout private repository
      uses: actions/checkout@v4
      with:
        repository: MaxMainio/nike
        token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
        path: nike
        
    # Step 3: Copy the contents of the 'nike' directory (private repo) into the public repo workspace.
    - name: Copy contents from private repo to public repo directory
      run: |
        cp -r nike/ ./

    # Step 4: Deploy everything.
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
